---

- name: create mysql directories
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /usr/local/var
    - /usr/local/var/mysql
    - /usr/local/var/log/
    - /Users/{{ lookup('env','USER') }}/Library/LaunchAgents

- name: install MySQL server
  homebrew: name={{ item }} state=latest
  with_items:
    - mysql

- name: install launchagents
  file: src=/usr/local/opt/mysql/homebrew.mxcl.mysql.plist path=~/Library/LaunchAgents/homebrew.mxcl.mysql.plist state=link force=yes

- name: check if MySQL is loaded
  shell: launchctl list
  changed_when: False
  register: mysql_loaded_result

- name: launch mysql
  shell: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
  when: "'homebrew.mxcl.mysql' not in mysql_loaded_result.stdout"

- pause: seconds=5

- name: check if the root password needs to be set.
  shell: if mysqladmin --user=root --password="" version; then rm -f /usr/local/var/log/mysql-root-user.done; mysql -uroot -e "UPDATE mysql.user SET Password = PASSWORD(\"{{ mysql_root_password }}\") WHERE User = \"root\"; DELETE FROM mysql.user WHERE User=\"\"; DELETE FROM mysql.user WHERE User=\"root\" AND Host NOT IN (\"localhost\", \"127.0.0.1\", \"::1\"); DROP DATABASE IF EXISTS test; FLUSH PRIVILEGES;"; touch /usr/local/var/log/mysql-root-user.done; fi
  args:
    creates: /usr/local/var/log/mysql-root-user.done

